package com.kizune.bucks.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1D7874)
val md_theme_light_onPrimary = Color(0xFFF8F8F8)
val md_theme_light_primaryContainer = Color(0xFFC7DDDD)
val md_theme_light_onPrimaryContainer = Color(0xFF141616)
val md_theme_light_secondary = Color(0xFFA0D2DB)
val md_theme_light_onSecondary = Color(0xFF204D55)
val md_theme_light_secondaryContainer = Color(0xFFB2D7DE)
val md_theme_light_onSecondaryContainer = Color(0xFF1F4249)
val md_theme_light_tertiary = Color(0xFF476262)
val md_theme_light_onTertiary = Color(0xFFECF8F7)
val md_theme_light_tertiaryContainer = Color(0xFFA3CAC1)
val md_theme_light_onTertiaryContainer = Color(0xFF283430)
val md_theme_light_error = Color(0xFFE85353)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410003)
val md_theme_light_background = Color(0xFFFAFDFB)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFB)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E3)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7978)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4EDAD4)

val md_theme_dark_primary = Color(0xFF9BDFDB)
val md_theme_dark_onPrimary = Color(0xFF3D3D3D)
val md_theme_dark_primaryContainer = Color(0xFF4F7270)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFF5196A3)
val md_theme_dark_onSecondary = Color(0xFF13363D)
val md_theme_dark_secondaryContainer = Color(0xFF52A39F)
val md_theme_dark_onSecondaryContainer = Color(0xFF142A2E)
val md_theme_dark_tertiary = Color(0xFF4E6E6E)
val md_theme_dark_onTertiary = Color(0xFFF5FFFE)
val md_theme_dark_tertiaryContainer = Color(0xFF73AC9F)
val md_theme_dark_onTertiaryContainer = Color(0xFF184B40)
val md_theme_dark_error = Color(0xFFAD2121)
val md_theme_dark_errorContainer = Color(0xFF700006)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFFF6B4AC)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C7)
val md_theme_dark_outline = Color(0xFF889391)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006A66)

val seed = Color(0xFF1D7874)